pipeline {
    agent any

    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is this a Release Candidate?')
    }

    environment {
        VERSION = "0.1.0"        
        VERSION_RC = "rc.2"
    }
    stages {
        stage('Audit tools') {                        
            steps {
                powershell '''
                  git version
                  dotnet --list-sdks
                  dotnet --list-runtimes
                '''
            }
        }
        stage('Build') {

             environment {
                VERSION_SUFFIX = "${powershell(script:'if ("${RC}" == "false") ; then echo -n "${VERSION_RC}+ci.${BUILD_NUMBER}"; else echo -n "${VERSION_RC}"; fi', returnStdout: true)}"
            }

            steps {
              echo "Building version: ${VERSION} with suffix: ${VERSION_RC}"
              powershell 'dotnet build -p:VersionPrefix="${VERSION}" --version-suffix "${VERSION_SUFFIX}" ./Pi.Web/Pi.Web.csproj'
            }
        }
        stage('Unit Test') {
            steps {
              
                powershell '''
                    dotnet test --logger "trx;LogFileName=Pi.Math.trx" Pi.Math.Tests/Pi.Math.Tests.csproj
                    dotnet test --logger "trx;LogFileName=Pi.Runtime.trx" Pi.Runtime.Tests/Pi.Runtime.Tests.csproj
                '''
                mstest testResultsFile:"**/*.trx", keepLongStdio: true
              
            }
        }
        stage('Smoke Test') {
            steps {
              powershell 'dotnet ./Pi.Web/bin/Debug/netcoreapp3.1/Pi.Web.dll'
            }
        }

        stage('Publish') {
            when {
                expression { return params.RC }
            } 
            steps {
                powershell 'dotnet publish -p:VersionPrefix="${VERSION}" --version-suffix "${VERSION_RC}" Pi.Web/Pi.Web.csproj -o ./out'
                archiveArtifacts('out/')
            }
        }
    }
}

